<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'surname', 'father_name', 'phone', 'email', 'telegram', 'type', 'entity_type', 'title', 'inn', 'kpp', 'ogrn', 'okpo', 'okved', 'address', 'ceo', 'rs', 'ks', 'bik', 'bank', 'source', 'balance', 'full_name', 'director_title', 'director_for_contract', 'legal_statement'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Customer $model) {
            if ($model->type === 'individual') {
                $model->title = "$model->name $model->surname";
            }
        });

        self::updating(function (Customer $model) {
            if ($model->type === 'individual') {
                $model->title = "$model->name $model->surname";
            }
        });
    }

    public function contracts()
    {
        return $this->hasMany(Contract::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function getTitleAttribute($value)
    {
        if (!$value) {
            return "$this->name $this->surname";
        }
        return $value;
    }

    public function scopeSearch($query, $search)
    {
        return $query->where(function ($q) use ($search) {
            $q->where("name", "like", "%$search%")
                ->orWhere("surname", "like", "%$search%")
                ->orWhere("email", "like", "%$search%")
                ->orWhere("phone", "like", "%$search%")
                ->orWhere("inn", "like", "%$search%")
                ->orWhere("title", "like", "%$search%");
        });
    }

    public function updateBalance(float $expense = 0, float $income = 0)
    {
        $this->balance = $this->balance - $expense + $income;
        $this->save();
    }
}
