<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'surname', 'father_name', 'phone', 'email', 'telegram', 'type', 'entity_type',
        'title', 'inn', 'kpp', 'ogrn', 'okpo', 'okved', 'address', 'ceo', 'rs', 'ks', 'bik', 'bank', 'source',
        'balance', 'full_name', 'director_title', 'director_for_contract', 'legal_statement', 'comment'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Customer $model) {
            if ($model->type === 'individual') {
                $model->title = "$model->name $model->surname";
            }
        });

        self::updating(function (Customer $model) {
            if ($model->type === 'individual') {
                $model->title = "$model->name $model->surname";
            }
        });
    }

    public function user()
    {
        return $this->hasOne(User::class);
    }

    public function contracts()
    {
        return $this->hasMany(Contract::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function recentOrders()
    {
        return $this->orders()
            ->where("date", ">=", Carbon::now()->startOfMonth())
            ->where("date", "<=", Carbon::now()->endOfMonth());
    }

    public function payments()
    {
        return $this->hasManyThrough(Payment::class, Order::class);
    }

    public function recentPayments()
    {
        return $this->payments()
            ->where("paid_at", ">=", Carbon::now()->startOfMonth())
            ->where("paid_at", "<=", Carbon::now()->endOfMonth());
    }

    public function lastPaidPayment()
    {
        return $this->hasOneThrough(Payment::class, Order::class)
            ->whereNotNull("paid_at")
            ->orderBy("paid_at", "desc");
    }


    public function newsletters()
    {
        return $this->belongsToMany(Newsletter::class);
    }

    public function getTitleAttribute($value)
    {
        if (!$value) {
            return "$this->name $this->surname";
        }
        return $value;
    }

    public function scopeSearch($query, $search)
    {
        return $query->where(function ($q) use ($search) {
            $q->where("name", "like", "%$search%")
                ->orWhere("surname", "like", "%$search%")
                ->orWhere("email", "like", "%$search%")
                ->orWhere("phone", "like", "%$search%")
                ->orWhere("inn", "like", "%$search%")
                ->orWhere("title", "like", "%$search%");
        });
    }

    public function updateBalance(float $expense = 0, float $income = 0)
    {
        $this->balance = $this->balance - $expense + $income;
        $this->save();
    }
}
